name: Release Modules

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  Release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          submodules: true
      - name: Create Zipped Artifact
        run: zip -r dragonbane-official-soundtrack.zip playlist/ packs/ module.json
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.PAT }}
          artifacts: "module.json, dragonbane-official-soundtrack.zip"
          generateReleaseNotes: true
          draft: true
          artifactErrorsFailBuild: true
